{% set name = "cdflib" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f239c209bf6b2c25971d44340bc65f0aba8ddc44085e7c7c614812936d61e259

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5
    - pip
    - twine >=1.11
  run:
    - python >=3.5
    - numpy

test:
  imports:
    - cdflib

about:
  home: https://github.com/MAVENSDC/cdflib
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A python CDF reader toolkit
  description: |
    A python CDF reader toolkit
  doc_url: https://cdflib.readthedocs.io/en/latest/
  dev_url: https://github.com/MAVENSDC/cdflib

extra:
  recipe-maintainers:
    - dstansby
    - Alexs12
