{% set name = "cdflib" %}
{% set version = "1.0.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c101c45a44d55d93ea4bf244009858e5f67160503414f0f021621e52d71bf261


build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5
    - pip
    - twine >=1.11
  run:
    - astropy
    - python >=3.5
    - numpy
    - xarray

test:
  imports:
    - cdflib
  commands:
    - pip check
  requires:
    - astropy
    - pip
    - xarray

about:
  home: https://github.com/MAVENSDC/cdflib
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A python CDF reader toolkit
  description: |
    A python CDF reader toolkit
  doc_url: https://cdflib.readthedocs.io/en/latest/
  dev_url: https://github.com/MAVENSDC/cdflib

extra:
  recipe-maintainers:
    - dstansby
    - Alexs12
